site_name: LFPH Implementers Forum
theme: 
  name: material
  features:
    - instant
  palette:
    scheme: preference
    primary:
    accent: 
  favicon: img/favicon.ico
  logo: img/lfph-icon-white.svg
repo_name: LFPH
repo_url: https://github.com/lfph/implementers-forum
nav:
  - 'index.md'
  - 'getting-started.md'
  - 'Documentation':
    - 'measurements-and-attenuation'
    - 'user-research.md'
    - 'analytics.md'
    - 'equity-and-inclusion.md'
  - 'Contributors'
extra_css:
  - css/extra.css
extra: 
  social: 
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/lfpubhealth 